# Generated by Django 5.0.6 on 2025-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionresult',
            name='slot_id',
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='status',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='occupied',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
